Roll Depot Tools from f80f5bc99e8c to 0f565fa8583d (8 revisions)
https://skia.googlesource.com/buildbot.git/+log/f80f5bc99e8c..0f565fa8583d

2025-09-04 ukai@google.com siso: add .sisorc support
2025-09-04 ayatane@chromium.org auth: Refactor missing access_token logic
2025-09-04 ukai@google.com ninja: fix TypeError: check_out_dir() missing 1 required positional argument
2025-09-03 ayatane@chromium.org auth: Remove unused param
2025-09-03 ayatane@chromium.org auth: Hoist exception handling in GerritAuthenticator
2025-09-03 ayatane@chromium.org auth: Disable ReAuth for git-credential-luci in depot_tools
2025-09-03 qjw@chromium.org roll git-credential-luci to improve error messaging
2025-09-03 qjw@chromium.org roll luci-auth-ssh-helper to support ping/pong check

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/depot-tools-skia-infra
Please CC borenet@google.com,skiabot@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Depot Tools: https://bugs.chromium.org/p/chromium/issues/entry
To file a bug in Skia Infra: https://bugs.chromium.org/p/skia/issues/entry

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Tbr: borenet@google.com
Change-Id: Ifa2e4ba59c90bb6503998a4acbf04a020e62361b
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/1049451
Commit-Queue: skia-autoroll <skia-autoroll@skia-public.iam.gserviceaccount.com>
Bot-Commit: skia-autoroll <skia-autoroll@skia-public.iam.gserviceaccount.com>