[gold] imgloader_test.go: Disable tests that are currently failing on Windows.
Error below:

=== RUN   TestImageLoaderGetSingleDigestNotFound
--- FAIL: TestImageLoaderGetSingleDigestNotFound (0.19s)
    imgloader_test.go:139: PASS:	Bucket()
    imgloader_test.go:139: PASS:	GetFileObjectAttrs(mock.AnythingOfTypeArgument,string)
    testutils.go:118:
        	Error Trace:	testutils.go:118
        	            				testutils.go:127
        	            				imgloader_test.go:139
        	Error:      	Received unexpected error:
        	            	remove c:\b\s\w\itomzyaa\testutils033018235\diffstore_failures\diffstore_failures.db: The process cannot access the file because it is being used by another process.
        	Test:       	TestImageLoaderGetSingleDigestNotFound

I suspect the cause is that the ImageHandler's FailureStore never closes the BoltDB file handle. Thus we get the error above when the deferred tearDown() call tries to remove the temporary directory where the DB file is located.

I'm temporarily disabling this test case, and TestImageLoaderGetMultipleDigestsDigest1FoundInBucketDigest2NotFound as well, which is probably subject to the same problem.

I'll make changes to ImageLoader in a follow-up CL to inject a FailureStore as a constructor parameter, and I'll inject a mock FailureStore from tests, which should fix these broken test cases on Windows.

Change-Id: I784be6622e4afb334e5218746d9f2e64530fc8aa