[Autoroller] Add "--force-sync" to "repo sync"
To avoid errors like:
"""
error.GitError: --force-sync not enabled; cannot overwrite a local work tree. If you're comfortable with the possibility of losing the work tree's git metadata, use repo sync --force-sync external/skia to proceed.
"""
Should be safe to do since we do not care about any local changes.

Change-Id: I1ae51746fd762561949abb484b4e67e43636ddb3