[bazel] Update rules_nodejs to 3.4.0 and rules_sass to 1.32.8.
Minor changes to TypeScript files were necessary to make the following check go away:

    error TS21231: [tsetse] type assert `JSON.parse() as SomeExplicitType` for type & optimization safety.

Bug: skia:10614
Change-Id: I4500386e4f72358571867a7c77da7ba79e283d60