[machines] BUILD rules for machine-server-sk.
Build with:

  $ bazel build //infra-sk/... //machine/modules/...

Test with:

  $ bazel test //infra-sk/... //machine/modules/...

Notes:
- I added some await statements to machine-server-sk.ts because otherwise the Bazel build fails with "error TS21225: [tsetse] All Promises in async functions must either be awaited or used in an expression.". See http://tsetse.info/must-use-promises.
- Changed //infra-sk:elements-sk_umd to include index.js files from the elements-sk NPM package and exclude any CSS imports in said files.
- For some reason, imports such as "import 'elements-sk/error-toast-sk'" do not resolve to error-toast-sk/index.js under the Bazel build, so I had to update some imports in machine-server-sk.ts.

Bug: skia:10614
Change-Id: Ie014994b7e5c9ef9f1431fd0e707201246e805a1