Update google.golang.org/grpc from v1.45.0 to v1.46.0.
On patchset 1, I updated google.golang.org/grpc from v1.45.0 to v1.46.0. This caused the following compilation error:

$ bazel build --config=remote //...
...
ERROR:
...
external/com_github_bazelbuild_remote_apis_sdks/go/pkg/client/client.go:415:27: undefined: grpc.WithBalancerName

The cause of this error is that github.com/bazelbuild/remote-apis-sdks at the revision in //go.mod uses grpc.WithBalancerName, which was deleted in google.golang.org/grpc v1.46.0, see release notes: https://github.com/grpc/grpc-go/releases/tag/v1.46.0.

On patchset 2, I tried updating to a newer github.com/bazelbuild/remote-apis-sdks version that would address the grpc.WithBalancerName issue, but I found that they updated rules_go in an earlier commit: https://github.com/bazelbuild/remote-apis-sdks/pull/328. This commit migrated the BUILD.bazel files in that repository to the new rules_go naming convention that drops the "go_default_library" name: https://github.com/bazelbuild/rules_go#what-s-up-with-the-go-default-library-name. Thus, I updated //go_repositories.bzl so that any references in our code to github.com/bazelbuild/remote-apis-sdks would use the correct Bazel labels without the "go_default_library" part.

On patchset 3, I updated github.com/bazelbuild/remote-apis-sdks to the oldest commit that removes all references of grpc.WithBalancerName: https://github.com/bazelbuild/remote-apis-sdks/pull/418. This update revealed the following compilation errors:

$ bazel build --config=remote //...
...
ERROR: ...
go/cas/rbe/rbe.go:92:13: cannot use client (variable of type *client.Client) as type RBEClient in struct literal:
        *client.Client does not implement RBEClient (wrong type for ComputeMerkleTree method)
                have ComputeMerkleTree(execRoot string, workingDir string, remoteWorkingDir string, is *"github.com/bazelbuild/remote-apis-sdks/go/pkg/command".InputSpec, cache filemetadata.Cache) (root digest.Digest, inputs []*uploadinfo.Entry, stats *client.TreeStats, err error)
                want ComputeMerkleTree(execRoot string, is *"github.com/bazelbuild/remote-apis-sdks/go/pkg/command".InputSpec, chunkSize int, cache filemetadata.Cache) (root digest.Digest, inputs []*chunker.Chunker, stats *client.TreeStats, err error)
go/cas/rbe/rbe.go:350:26: undefined: chunker.NewFromProto
go/cas/rbe/rbe.go:512:24: undefined: chunker.NewFromProto

Patchset 3 includes my attempt at fixing said errors. After those errors went away, I saw compilation errors in //cabe/go/backends/rbecas_helpers.go due to a change in the return types of some functions. Patchset 3 addresses those errors as well.

borenet@: Please triple-check my RBE changes. I'm unfamiliar with these APIs. My success criteria was that the code compiles successfully and that the unit tests pass.

Bug: b/308044304
Change-Id: I7d7b3e9069497fce2d4ad864fc6e6aad19410b45
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/771501
Reviewed-by: Eric Boren <borenet@google.com>
Reviewed-by: Joe Gregorio <jcgregorio@google.com>
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: Sean McCullough <seanmccullough@google.com>