[ct] task-queue-sk_test.js: Fix assertion.
This fixes the following error:

  Error: Invalid Chai property: class. Did you mean "has"?

Somehow the "expect(...).to.have.class('foo')" syntax stopped working after moving to the TypeScript-enabled Webpack configuration. Probably some kind of issue with the npm dependencies.

Two possible fixes:

1. Rewrite test to make an assertion directly against the element's className property.
2. Explicitly add support for the "to.have.class" syntax via chai-dom[1] and karma-chai-dom[2].

I chose to go with option 1 because it's the simplest and because AFAIK there's no other test in the repo that uses this syntax, but we can always switch to option 2 if anyone is interested.

[1] https://github.com/nathanboktae/chai-dom.
[2] https://github.com/nathanboktae/karma-chai-dom.

Bug: skia:10292
Change-Id: I8fcfaa9c2d3373558b3f97b2848f0950794f17eb