Update CIPD to go 1.9
In Go 1.9, they added a monotonic clock to the time.Time objects
https://golang.org/pkg/time/#hdr-Monotonic_Clocks

time.Now() includes the monotonic part, but many other ways to create
time do not (e.g. time.Date(...)).  Tyring to compare these with 
reflect.DeepEquals yields something like:
(using testify/require.Equal):

Error:  Not equal: 
  expected: [...]
  actual: [...]
  
  Diff:
  --- Expected
  +++ Actual
  @@ -6,3 +6,3 @@
    },
  - Created: (time.Time) 2017-10-18 08:03:14.268400724 -0400 EDT m=+0.024290191,
  + Created: (time.Time) 2017-10-18 08:03:14.268400724 -0400 EDT,


To fix this, we remove the monotonic part using the 
"canonical" time.Now().Round(0).  This is "safe" in that code will
act like Go 1.8 w/o the monotonic portion.  This monotonic part guards 
against wall clock changes like leap seconds.  AFAIK, our servers
have withstood leapseconds before w/o issue, so I do not believe there
to be much risk in this solution.

An ideal solution may be to write our own reflect.DeepEqual
that accounts for the monotonic time, but that seemed difficult
and error prone.

Bug: skia:
Change-Id: I3ee039b2558f550a30cb65a29a2b12ed87a01b94