Disabling smoothness and repaint from CT since they are crashing
Crash log:

[ RUN      ] http://www.facebook.com/

Unhandled exception while running http://www.facebook.com/

Traceback (most recent call last):
  _RunPage at tools/telemetry/telemetry/page/page_runner.py:530
    test.RunPage(page, page_state.tab, results)
  RunPage at tools/telemetry/telemetry/page/page_test.py:309
    self.ValidateAndMeasurePage(page, tab, results)
  ValidateAndMeasurePage at tools/perf/measurements/smoothness.py:40
    self._smoothness_controller.AddResults(tab, results)
  AddResults at tools/perf/measurements/smoothness_controller.py:110
    self._timeline_model, renderer_thread, smooth_records, results)
  AddResults at tools/telemetry/telemetry/web_perf/metrics/smoothness.py:22
    [r.GetBounds() for r in interaction_records])
  __init__ at tools/telemetry/telemetry/web_perf/metrics/rendering_stats.py:139
    if HasRenderingStats(browser_process):
  HasRenderingStats at tools/telemetry/telemetry/web_perf/metrics/rendering_stats.py:116
    if 'data' in event.args and event.args['data']['frame_count'] == 1:
KeyError: 'frame_count'

Locals:
  event   : TimelineEvent(name='BenchmarkInstrumentation::MainThreadRenderingStats', start=553.375000, duration=0.0, thread_start=None, thread_duration=None, {u'data': {u'painted_pixel_count': 0, u'paint_time': 0.0, u'recorded_pixel_count': 0, u'record_time': 0.0}})
  process : <telemetry.timeline.process.Process object at 0x20d96d0>

Traceback (most recent call last):
  File "third_party/chromium_trunk/src/tools/perf/../telemetry/telemetry/page/page_runner.py", line 530, in _RunPage
    test.RunPage(page, page_state.tab, results)
  File "third_party/chromium_trunk/src/tools/perf/../telemetry/telemetry/page/page_test.py", line 309, in RunPage
    self.ValidateAndMeasurePage(page, tab, results)
  File "/b/skia-repo/buildbot/third_party/chromium_trunk/src/tools/perf/measurements/smoothness.py", line 40, in ValidateAndMeasurePage
    self._smoothness_controller.AddResults(tab, results)
  File "/b/skia-repo/buildbot/third_party/chromium_trunk/src/tools/perf/measurements/smoothness_controller.py", line 110, in AddResults
    self._timeline_model, renderer_thread, smooth_records, results)
  File "third_party/chromium_trunk/src/tools/perf/../telemetry/telemetry/web_perf/metrics/smoothness.py", line 22, in AddResults
    [r.GetBounds() for r in interaction_records])
  File "third_party/chromium_trunk/src/tools/perf/../telemetry/telemetry/web_perf/metrics/rendering_stats.py", line 139, in __init__
    if HasRenderingStats(browser_process):
  File "third_party/chromium_trunk/src/tools/perf/../telemetry/telemetry/web_perf/metrics/rendering_stats.py", line 116, in HasRenderingStats
    if 'data' in event.args and event.args['data']['frame_count'] == 1:
KeyError: 'frame_count'

[  FAILED  ] http://www.facebook.com/ (11188 ms)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ]  http://www.facebook.com/

1 FAILED TEST

page_name,board_temperature (celsius)
http://www.facebook.com/,31.0