Update patch set 1
Patch Set 1:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 155182: Change could not be merged because the commit is empty. Project policy requires all commits to contain modifications to at least one file.

Patch-set: 1
Tag: autogenerated:cq:full-run