[perf] Gracefully handle trace values duplicates
Should fix errors like `pgx - Exec map[args:[] err:ERROR:
com.google.api.gax.rpc.OutOfRangeException:
io.grpc.StatusRuntimeException: OUT_OF_RANGE: Cannot affect a row second
time for key (<unprintable>, 42) (SQLSTATE P0001) pid:44 sql:INSERT
INTO`. There is no reason to drop the whole batch of data because of the
duplicates.

Change-Id: I412ac5d8445b356c150bf4f170776d0758b7aaef
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/1124858
Reviewed-by: Maxim Sheshukov <maximsheshukov@google.com>
Commit-Queue: Anri Sidorov <ansid@google.com>