[gold] imgloader_test.go: Disable tests that are currently failing on Windows.
Error below:

=== RUN   TestImageLoaderGetSingleDigestNotFound
--- FAIL: TestImageLoaderGetSingleDigestNotFound (0.19s)
    imgloader_test.go:139: PASS:	Bucket()
    imgloader_test.go:139: PASS:	GetFileObjectAttrs(mock.AnythingOfTypeArgument,string)
    testutils.go:118:
        	Error Trace:	testutils.go:118
        	            				testutils.go:127
        	            				imgloader_test.go:139
        	Error:      	Received unexpected error:
        	            	remove c:\b\s\w\itomzyaa\testutils033018235\diffstore_failures\diffstore_failures.db: The process cannot access the file because it is being used by another process.
        	Test:       	TestImageLoaderGetSingleDigestNotFound

I suspect the cause is that the failure store never closes the Bolt database file handle, thus when the tearDown() function is called and tries to remove the temporary directory where the database file is stored, it fails with the error above.

I'm disabling this test case and TestImageLoaderGetMultipleDigestsDigest1FoundInBucketDigest2NotFound for now as it's probably subject to the same problem.

I'll mock out the ImageLoader failure store in a followup CL, which should fix the problem, and then reenable these tests.

Change-Id: I784be6622e4afb334e5218746d9f2e64530fc8aa