[run_emulators] tell gcloud to use default answers for user prompts
This is to handle cases where someone runs the run_emulators script
in an environment where e.g. some required gcloud components are not
already installed, and gcloud asks if the user wants to install them.

Adding the -quiet flag tells gcloud to just use the default answer in
these cases rather than waiting for user input. For the missing gcloud
component installation prompts, the default answer is `Y`, so this will
make it install any missing glcoud components before proceeding.

/tmp/cloud_emulators.log Before:

```
Your current Google Cloud CLI version is: 449.0.0
Installing components from version: 449.0.0

┌─────────────────────────────────────────────┐
│     These components will be installed.     │
├──────────────────────┬────────────┬─────────┤
│         Name         │  Version   │   Size  │
├──────────────────────┼────────────┼─────────┤
│ gcloud Beta Commands │ 2023.10.02 │ < 1 MiB │
└──────────────────────┴────────────┴─────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Once started, canceling this operation may leave your SDK installation in an inconsistent state.

Do you want to continue (Y/n)?
ERROR: (gcloud) This prompt could not be answered because you are not in an interactive session.  You can re-run the command with the --quiet flag to accept default answers for all prompts.
For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Once started, canceling this operation may leave your SDK installation in an inconsistent state.

Do you want to continue (Y/n)?
ERROR: (gcloud) This prompt could not be answered because you are not in an interactive session.  You can re-run the command with the --quiet flag to accept default answers for all prompts.
For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Once started, canceling this operation may leave your SDK installation in an inconsistent state.

Do you want to continue (Y/n)?
ERROR: (gcloud) This prompt could not be answered because you are not in an interactive session.  You can re-run the command with the --quiet flag to accept default answers for all prompts.
For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Once started, canceling this operation may leave your SDK installation in an inconsistent state.

Do you want to continue (Y/n)?
ERROR: (gcloud) This prompt could not be answered because you are not in an interactive session.  You can re-run the command with the --quiet flag to accept default answers for all prompts.
```

/tmp/cloud_emulators.log After:

```

Your current Google Cloud CLI version is: 449.0.0
Installing components from version: 449.0.0


┌─────────────────────────────────────────────┐
Your current Google Cloud CLI version is: 449.0.0

Installing components from version: 449.0.0
│     These components will be installed.     │

├──────────────────────┬────────────┬─────────┤
│         Name         │  Version   │   Size  │
├──────────────────────┼────────────┼─────────┤
│ gcloud Beta Commands │ 2023.10.02 │ < 1 MiB │
└──────────────────────┴────────────┴─────────┘

┌─────────────────────────────────────────────┐
│     These components will be installed.     │
├──────────────────────┬────────────┬─────────┤
│         Name         │  Version   │   Size  │
├──────────────────────┼────────────┼─────────┤
│ gcloud Beta Commands │ 2023.10.02 │ < 1 MiB │
└──────────────────────┴────────────┴─────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Performing in place update...

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Performing in place update...

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Performing in place update...

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

Performing in place update...
```

Change-Id: I22094dba3ecd58780eb0a9d0877331574292183c
Reviewed-on: https://skia-review.googlesource.com/c/buildbot/+/795970
Reviewed-by: Joe Gregorio <jcgregorio@google.com>
Commit-Queue: Sean McCullough <seanmccullough@google.com>
Reviewed-by: Leandro Lovisolo <lovisolo@google.com>